In [2]:
"""‹ 
主要内容：
 Data types
‹ Array types
‹ Type conversions
‹ Array creation
‹ Indexing
‹ Slicing
‹ Shape manipulation
"""
import numpy as np

The history saving thread hit an unexpected error (OperationalError('disk I/O error',)).History will not be written to the database.


In [21]:
# ndarray 包括实际的数据以及描述这些数据的相关信息
# 使用arange创建adarray
a = np.arange(4)
# 使用dtype获得adarray中元素的数据类型
type(a), a.dtype, a

(numpy.ndarray, dtype('int32'), array([0, 1, 2, 3]))

In [22]:
# 获得数组维度信息“对于多维数组
# 当数组为矩阵，shape为（行，列）tuple，对于单维数组，shape为只有一个元素的tuple，却值为该数组的长度”
# 对于维度不相同的数组，shape第一个值返回的行数
a.shape, type(a.shape)         

((4,), tuple)

In [24]:
# 创建一个多维数组，并显示其维度
m = np.array([np.arange(3), np.arange(3), np.arange(3)])
print m 
print "shape:", m.shape

[[0 1 2]
 [0 1 2]
 [0 1 2]]
shape: (3, 3)


In [25]:
# 选择对角线上的元素（使用a[m, n]来提取响应位置的元素）
m[0,0], m[1,1], m[2,2] 

(0, 1, 2)

In [6]:
# 学习Dtype对象
a = np.arange(10, dtype='d')  # 双精度
a.dtype, a.dtype.itemsize

(dtype('float64'), 8)

In [7]:
b = np.arange(10, dtype='i')  # 整型
b.dtype, b.dtype.itemsize

(dtype('int32'), 4)

In [10]:
# 类型字符
np.dtype(float), np.dtype(int), np.dtype(str)

(dtype('float64'), dtype('int32'), dtype('S'), dtype('float64'))

In [13]:
np.dtype('i'), np.dtype('f'), np.dtype('d'), np.dtype('b')

(dtype('int32'), dtype('float32'), dtype('float64'), dtype('int8'))

In [18]:
# dtype的属性
t = np.dtype('uint64')
t.char  # 获得类型对应的字符 

'Q'

In [28]:
b = np.arange(24)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [57]:
# 
b = b.reshape(2, 3, 4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [60]:
# 选取单个元素
b[0, 0, 0]

0

In [63]:
# 选取,想忽略哪个维度就用:
print b[:, 0, 0]  # 
print b[0,:,:]
print b[0,0,:]

[ 0 12]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]


In [76]:
# 降维，返回的是b的view，即不会重新分配内存
print b.ravel()
print type(b.ravel)
ravel = b.ravel()
id(ravel), id(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
<type 'builtin_function_or_method'>


(89668288, 89545808)

In [78]:
# 与ravel结果相同，但是重新分配内存，返回一个新的对象
print b.flatten()
print type(b.flatten)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
<type 'builtin_function_or_method'>


In [81]:
# 改变b的shape
b.shape = (6, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [83]:
# 与reshape
b.resize((2,3,4))
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])